#
version: 2
jobs:
  build:
    # machine: true
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t praqma/qe-test:$TAG .      # (4)
          docker login -u $DOCKER_USER -p $DOCKER_PASS         # (5)
          docker push praqma/qe-test:$TAG


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
