version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    environment:
      - TAG: praqma/questionnaire-engine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set environment variable
          command: |
            source version.sh $$ echo 'export VERSION=$VERSION.$CIRCLE_BUILD_NUM' >> $BASH_ENV
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Build back and front-end source code (transpile to ES5)
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Login to Docker hub
          command: docker login --username $DOCKER_USER --password "$DOCKER_PASS"
      - run:
          name: Build Docker image
          command: |
            docker build --tag $TAG:$VERSION .
      # - run:        // Removed for now...
      #     name: Run container
      #     command: |
      #       docker run -d --rm -it -p 3000:3000 --name engine $TAG:$VERSION npm start
      #       docker stop engine
      - run:
          name: Deploy to Dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push $TAG:$VERSION
            fi
