#
version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - run:
        name: Build Docker image
        command: docker build -t qe-test:1.0 .
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy
