version: 2
jobs:
  build:
    # machine: true
    docker:
      - image: circleci/node:8.9.4
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build --tag praqma/qe-test:$TAG .
          docker login --username $DOCKER_USER --password-stdin "$DOCKER_PASS"
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker push praqma/qe-test:$TAG
          fi
