version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    environment:
      - TAG: praqma/questionnaire-engine
    steps:
      - checkout
      - run:
          name: Set environment variables
          command: |
            source version.sh && echo "export VERSION=$VERSION.$CIRCLE_BUILD_NUM" >> $BASH_ENV
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json"}}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: Build back and front-end source code (transpile to ES5)
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      # Code after this line will be executed on a remote docker host
      # thus only a Docker environment will be available from this step (no linux packages)
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build --tag $TAG:$VERSION .
      - run:
          name: Save docker image and vars
          command: |
            docker save $TAG:$VERSION > ~/docker-image.tar
            echo "IMAGE_NAME=$TAG:$VERSION" >> ~/vars.sh
            echo "VERSION=$VERSION" >> ~/vars.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - docker-image.tar
            - vars.sh
  deploy:
    docker:
      - image: circleci/node:8.9.4
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - run:
          name: Install dependencies (fargate, phantomjs)
          command: |
            sudo apt-get update && sudo apt-get install wget unzip -y
            cd /usr/local/bin
            sudo wget -O fargatecli.zip https://github.com/jpignata/fargate/releases/download/v0.2.3/fargate-0.2.3-linux-386.zip
            sudo unzip fargatecli.zip && sudo rm fargatecli.zip
            export PATH=$PATH:/.
            cd ~
            wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            sudo tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/
            sudo ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin

      # Code after this line will be executed on a remote docker host
      # thus only a Docker environment will be available from this step (no linux packages)
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/
      - run:
          name: Set environment variables
          command: |
            cd ~
            source vars.sh && echo "export VERSION=$VERSION" >> $BASH_ENV && echo "export IMAGE_NAME=$IMAGE_NAME" >> $BASH_ENV
            source $BASH_ENV && echo "export AWS_SERVICE_NAME_PROD=qe-prod-$(echo $VERSION | tr "." "-")" >> $BASH_ENV
      - run:
          name: Extract docker image archive
          command: docker load < ~/docker-image.tar
      - run:
          name: Deploy to Dockerhub
          command: |
            docker login --username $DOCKER_USER --password "$DOCKER_PASS"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              source $BASH_ENV && docker push $IMAGE_NAME   # source bash_env vars since it is not sourced by circleci
            fi
      - add_ssh_keys:
          fingerprints:
            - "e0:5e:f9:7b:80:7f:48:0a:2f:d9:f7:27:2b:c3:75:9a"
      # Check out git again so we can tag the deployed version
      - checkout:
          path: ~/repo
      - run: pwd # remove this
      - run:
          name: Create service on AWS Fargate
          command: source $BASH_ENV && source ./scripts/create_service.sh $AWS_SERVICE_NAME_PROD $IMAGE_NAME test $DB_URI
      - run:
          name: Smoke-test the deployed website
          command: |
            phantomjs phantomTest.js $IP
      # This command removes all services except AWS_SERVICE_NAME_PROD - make sure it's defined by this point
      - run:
          name: Remove unused services
          command: |
            source /scripts/prune_services.sh
      - run:
          name: Tag deployed version on GitHub
          command: |
            source $BASH_ENV && git tag $VERSION
            git push origin --tags
      - run:
          name: DONE! Your IP address is...
          command: echo "Your IP address is $IP"

workflows:
  version: 2
  build-and-approval-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold

