version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    environment:
      - TAG: praqma/questionnaire-engine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Export interpolated environment variables
          command: |
            echo 'export VERSION=0.1.$CIRCLE_BUILD_NUM' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
      - run:
          name: Install env dependencies (fargate)
          command: |
            sudo apt-get update && sudo apt-get install wget unzip -y
            cd /usr/local/bin
            sudo wget -O fargatecli.zip https://github.com/jpignata/fargate/releases/download/v0.2.3/fargate-0.2.3-linux-386.zip
            sudo unzip fargatecli.zip && sudo rm fargatecli.zip
            export PATH=$PATH:/.
            cd /
            fargate service create latest-service --image praqma/questionnaire-models:0.1.15 --env DB_PASSWORD=$DB_PASSWORD
      # - run:
      #     name: Install npm dependencies
      #     command: npm install
      # - run:
      #     name: Build back and front-end source code (transpile to ES5)
      #     command: npm run build
      # - run:
      #     name: Run tests
      #     command: npm test
      # - run:
      #     name: Login to Docker hub
      #     command: docker login --username $DOCKER_USER --password "$DOCKER_PASS"
      # - run:
      #     name: Build Docker image
      #     command: |
      #       docker build --tag $TAG:$VERSION .
      # - run:
      #     name: Run container
      #     command: |
      #       docker run -d --rm -it -p 3000:3000 --name engine $TAG:$VERSION npm start
      #       docker stop engine
      # - run:
      #     name: Deploy to Dockerhub
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         docker push $TAG:$VERSION
      #       fi
      # - run:
      #     name: Deploy container instance on AWS
      #     command: fargate service create latest-service --image praqma/questionnaire-models:0.1.15 --env DB_PASSWORD=$DB_PASSWORD
