version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # install dependencies
      - run: npm install
      # build client and server side code (transpile to common.js)
      - run: npm run build
      # run mocha tests
      - run: npm test
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build --tag praqma/qe-test:$TAG .
          docker login --username $DOCKER_USER --password "$DOCKER_PASS"
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker push praqma/qe-test:$TAG
          fi
