version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    environment:
      - TAG: praqma/questionnaire-engine
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json"}}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: Build back and front-end source code (transpile to ES5)
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set environment variable
          command: |
            source version.sh && echo "export VERSION=$VERSION.$CIRCLE_BUILD_NUM" >> $BASH_ENV
      - run:
          name: Login to Docker hub
          command: docker login --username $DOCKER_USER --password "$DOCKER_PASS"
      - run:
          name: Build Docker image
          command: |
            docker build --tag $TAG:$VERSION .
      - run: mkdir -p docker
      - run:
          name: Save docker image
          command: docker save $TAG:$VERSION > docker/engine-image.tar
      - persist_to_workspace:
          root: docker
          paths:
            - engine-image.tar
      # - run:
      #     name: Deploy to Dockerhub
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         docker push $TAG:$VERSION
      #       fi
      # - add_ssh_keys:
      #     fingerprints:
      #       - "e0:5e:f9:7b:80:7f:48:0a:2f:d9:f7:27:2b:c3:75:9a"
      # - run:
      #     name: Tag version on GitHub
      #     command: |
      #       git tag $VERSION
      #       git push origin --tags


      # - run:        // Removed for now...
      #     name: Run container
      #     command: |
      #       docker run -d --rm -it -p 3000:3000 --name engine $TAG:$VERSION npm start
      #       docker stop engine
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    environment:
      - TAG: praqma/questionnaire-engine
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run: echo "VERSION=0.1.0" > version.sh
      - run:
          name: Set environment variable
          command: |
            source version.sh && echo "export VERSION=$VERSION.$CIRCLE_BUILD_NUM" >> $BASH_ENV

      - attach_workspace:
          at: ~/repo/docker
      - run: docker load < docker/engine-image.tar



workflows:
  version: 2
  build-and-approval-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
