version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    environment:
      - TAG: praqma/questionnaire-engine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build back and front-end source code (transpile to ES5)
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Login to Docker hub
          command: docker login --username $DOCKER_USER --password "$DOCKER_PASS"
      - run:
          name: Build Docker image
          command: |
            VERSION=0.1.$CIRCLE_BUILD_NUM
            docker build --tag $TAG:$VERSION .
      - run:
          name: Run container
          command: |
            docker run -d --rm -it -p 3000:3000 --name engine $TAG
            docker stop engine
      - run:
          name: Deploy to Dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push $TAG:$VERSION
            fi
